version: "3"

networks:
  selenium:

services:
  python:
    container_name: python
    tty: true
    build:
      dockerfile: .docker/python/Dockerfile
    volumes:
      - ./app:/app
    working_dir: /app
    depends_on:
      - selenium-hub
    networks:
      - selenium

  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_GRID_MAX_SESSION=5
    networks:
      - selenium

  chrome:
    image: selenium/node-chrome:4.15.0
    container_name: chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium

  firefox:
    image: selenium/node-firefox:4.15.0
    container_name: firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5901:5900"
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium
